- archive.shriftweb.org
- archive.skyehawke.com
- archiveofourown.org
- ashwinder.sycophanthex.com
- bloodshedverse.com
- bloodties-fans.com
- buffygiles.velocitygrass.com
- chaos.sycophanthex.com
- chosentwofanfic.com
- csi-forensics.com
- dark-solace.org
- efiction.esteliel.de
- efpfanfic.net
- erosnsappho.sycophanthex.com
- fanfic.castletv.net
- fanfic.hu
- fanfic.potterheadsanonymous.com
- fanfiction-junkies.de
- fannation.shades-of-moonlight.com
- fictionhunt.com
- fictionmania.tv
- fictionpad.com
- ficwad.com
- finestories.com
- forum.questionablequesting.com
- forums.spacebattles.com
- forums.sufficientvelocity.com
- gluttonyfiction.com
- gravitytales.com
- harrypotterfanfiction.com
- hlfiction.net
- hpfanficarchive.com
- imagine.e-fic.com
- inkbunny.net
- it-could-happen.net
- ksarchive.com
- lcfanfic.com
- literotica.com
- lotrfanfiction.com
- lumos.sycophanthex.com
- mcstories.com
- merlinfic.dtwins.co.uk
- mtt.just-once.net
- ncisfiction.com
- nfacommunity.com
- nha.magical-worlds.us
- ninelivesarchive.com
- novelonlinefull.com
- noveltrove.com
- occlumency.sycophanthex.com
- ponyfictionarchive.net
- pretendercentre.com
- quotev.com
- samandjack.net
- sebklaine.net
- sheppardweir.com
- sinful-dreams.com/unicorn/fic
- sinful-dreams.com/whispered/muse
- sinful-dreams.com/wicked/temptation
- spikeluver.com
- starslibrary.net
- storiesonline.net
- sword.borderline-angel.com
- tasteofpoison.inkubation.net
- test1.com
- tgstorytime.com
- thehookupzone.net
- themaplebookshelf.com
- themasque.net
- trekfanfiction.net
- trekiverse.org
- voracity2.e-fic.com
- www.13hours.org
- www.adastrafanfic.com
- www.adult-fanfiction.org
- www.alternatehistory.com
- www.andromeda-web.com
- www.aneroticstory.com
- www.asexstories.com
- www.asianfanfics.com
- www.bdsmlibrary.com
- www.deandamage.com
- www.deepinmysoul.net
- www.destinysgateway.com
- www.dokuga.com
- www.dracoandginny.com
- www.fanficauthors.net
- www.fanfiction.net
- www.fanfiktion.de
- www.ficbook.net
- www.fictionalley.org
- www.fictionpress.com
- www.fimfiction.net
- www.fireflyfans.net
- www.giantessworld.net
- www.hentai-foundry.com
- www.ik-eternal.net
- www.libraryofmoria.com
- www.looselugs.com
- www.lotrgfic.com
- www.lushstories.com
- www.masseffect2.in
- www.mediaminer.org
- www.midnightwhispers.net
- www.mugglenetfanfiction.com
- www.naiceanilme.net
- www.narutofic.org
- www.novelall.com
- www.phoenixsong.net
- www.potionsandsnitches.org
- www.potterfics.com
- www.qaf-fic.com
- www.royalroad.com
- www.scarvesandcoffee.net
- www.siye.co.uk
- www.squidge.org/peja
- www.starskyhutcharchive.net
- www.storiesofarda.com
- www.sugarquill.net
- www.thedelphicexpanse.com
- www.thepetulantpoetess.com
- www.thundercatsfans.org
- www.tomparisdorm.com
- www.tthfanfic.org
- www.twilightarchives.com
- www.twilighted.net
- www.utopiastories.com
- www.valentchamber.com
- www.walkingtheplank.org
- www.wattpad.com
- www.webnovel.com
- www.whofic.com
- www.wolverineandrogue.com
- www.wraithbait.com
- www.wuxiaworld.co
- www.wuxiaworld.com