- author: nobody103
  dateChecked: 2019-07-26
  datePublished: 2011-10-17
  dateUpdated: 2019-06-12
  numChapters: 100
  numWords: 768372
  output_filename: Mother of Learning-fpcom_2961893.epub
  siteabbrev: fpcom
  storyPath: Fiction\Fantasy
  storyUrl: https://www.fictionpress.com/s/2961893/1/
  title: Mother of Learning
- author: Verona-mira
  dateChecked: 2019-07-26
  datePublished: 2018-08-10
  dateUpdated: 2018-12-23
  numChapters: 16
  numWords: 45903
  output_filename: Advancing Technology-fsb_670048.epub
  siteabbrev: fsb
  storyPath: Fiction\FanFic\Worm
  storyUrl: https://forums.spacebattles.com/threads/advancing-technology-worm-au.670048/
  title: Advancing Technology
- author: Aku-dono
  dateChecked: 2019-07-26
  datePublished: 2018-03-01
  dateUpdated: 2019-07-20
  numChapters: 39
  numWords: 202286
  output_filename: I Woke Up As a Dungeon_ Now What_-fsb_620521.epub
  siteabbrev: fsb
  storyPath: Fiction\FanFic\Worm
  storyUrl: https://forums.spacebattles.com/threads/i-woke-up-as-a-dungeon-now-what-dungeon-worm.620521/
  title: I Woke Up As a Dungeon, Now What?
- author: ack1308
  dateChecked: 2019-07-26
  datePublished: 2015-05-04
  dateUpdated: 2018-09-19
  numChapters: 21
  numWords: 181260
  output_filename: The Slippery Slope-ffnet_11227072.epub
  siteabbrev: ffnet
  storyPath: Fiction\FanFic\Worm
  storyUrl: https://www.fanfiction.net/s/11227072/1/
  title: The Slippery Slope
